version: '3.11'

networks:
  monitor:
    driver: overlay
    name: monitor
    external: true
  app:
    driver: overlay
    name: app
  
services:
  traefik:
    image: traefik:v3.3
    command:
      - "--configFile=/etc/traefik/traefik.yaml"
    environment:
      - FORCE=1
    networks:
      - monitor
      - app
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /opt/configs/traefik/traefik-v3.yaml:/etc/traefik/traefik.yaml:ro
      - /opt/configs/traefik/dynamic:/etc/traefik/dynamic:ro
    ports:
      - target: 80
        published: 80
        mode: host
      - target: 8080
        published: 8088
        protocol: tcp
        mode: ingress
      - target: 8082
        published: 8082
        mode: host
    deploy:
      mode: global
      resources:
        limits:
          cpus: '1'
          memory: 500M
        reservations:
          cpus: '0.5'
          memory: 100M
      placement:
        constraints: [node.role == manager]
      labels:
        - "traefik.enable=true"
        - "traefik.http.services.traefik.loadbalancer.server.port=8088"
        - "traefik.http.routers.traefik.entrypoints=web"
        - "traefik.http.routers.traefik.service=api@internal"
        - "traefik.http.routers.traefik.tls=false"
        - "traefik.swarm.network=monitor"
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
