version: '3.11'

networks:
  monitor:
    driver: overlay
    name: monitor
    external: true
  agent_network:
    driver: overlay
  
volumes:
  portainer_data:
  grafana_data:

services:
  portainer:
    image: portainer/portainer-ce:lts
    command: -H tcp://tasks.agent:9001 --tlsskipverify
    ports:
      - "9443:9443"
      - "9000:9000"
      - "8000:8000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - monitor
      - agent_network
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: '1'
          memory: 500M
        reservations:
          cpus: '0.25'
          memory: 100M
      placement:
        constraints: [node.role == manager]
      labels:
        - "traefik.enable=true"
        - "traefik.http.services.portainer.loadbalancer.server.port=9000"
        - "traefik.http.routers.portainer.entrypoints=web"
        - "traefik.http.routers.portainer.tls=false"
        - "traefik.swarm.network=monitor"
      restart_policy:
        condition: on-failure
  agent:
    image: portainer/agent:lts
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - agent_network
    deploy:
      mode: global
      resources:
        limits:
          cpus: '0.5'
          memory: 100M
        reservations:
          cpus: '0.25'
          memory: 50M
      placement:
        constraints: [node.platform.os == linux]
      labels:
        - "traefik.enable=false"
      restart_policy:
        condition: on-failure

  grafana:
    image: grafana/grafana:latest
    depends_on:
      - prometheus
      - traefik
    ports:
      - "3003:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - /opt/configs/grafana/provisioning/:/etc/grafana/provisioning/
    env_file:
      - /opt/configs/grafana/config.monitoring
    networks:
      - monitor
    user: "472"
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 500M
        reservations:
          cpus: '0.25'
          memory: 100M
      placement:
        constraints:
          - node.role==manager
      labels:
        - "traefik.enable=true"
        - "traefik.http.services.grafana.loadbalancer.server.port=3000"
        - "traefik.http.routers.grafana.entrypoints=web"
        - "traefik.http.routers.grafana.tls=false"
        - "traefik.swarm.network=monitor"
      restart_policy:
        condition: on-failure
