---
networks:
  monitor:
    driver: overlay
    name: monitor
    external: true
  agent_network:
    driver: overlay
  
volumes:
  portainer_data:
    external: true
  grafana_data:

services:
  portainer:
    image: portainer/portainer-ce:lts
    command: -H tcp://tasks.agent:9001 --tlsskipverify
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - monitor
      - agent_network
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: '1'
          memory: 500M
        reservations:
          cpus: '0.25'
          memory: 100M
      placement:
        constraints: [node.role == manager]
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.portainer.rule=Host(`cluster.maggielab.org`)"
        - "traefik.http.services.portainer.loadbalancer.server.port=9000"
        - "traefik.http.routers.portainer.entrypoints=websecure"
        - "traefik.http.routers.portainer.tls=false"
        - "traefik.swarm.network=monitor"
      restart_policy:
        condition: on-failure
  agent:
    image: portainer/agent:lts
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - agent_network
    deploy:
      mode: global
      resources:
        limits:
          cpus: '0.5'
          memory: 100M
        reservations:
          cpus: '0.25'
          memory: 50M
      placement:
        constraints: [node.platform.os == linux]
      labels:
        - "traefik.enable=false"
      restart_policy:
        condition: on-failure

  grafana:
    image: grafana/grafana:latest
    depends_on:
      - prometheus
      - traefik
    volumes:
      - grafana_data:/var/lib/grafana
      - /mnt/nfs/docker/configs/grafana/provisioning/:/etc/grafana/provisioning/
    env_file:
      - /mnt/nfs/docker/configs/grafana/config.monitoring
    networks:
      - monitor
    user: "472"
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 500M
        reservations:
          cpus: '0.25'
          memory: 100M
      placement:
        constraints:
          - node.role==manager
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.grafana.rule=Host(`grafana.maggielab.org`)"
        - "traefik.http.services.grafana.loadbalancer.server.port=3000"
        - "traefik.http.routers.grafana.entrypoints=websecure"
        - "traefik.http.routers.grafana.tls=false"
        - "traefik.swarm.network=monitor"
      restart_policy:
        condition: on-failure

  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    networks:
      - monitor
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 500M
        reservations:
          cpus: '0.25'
          memory: 100M
      placement:
        constraints:
          - node.role==manager
      labels:
        - "traefik.enable=true"
        - "traefik.http.services.homelab.loadbalancer.server.port=3000"
        - "traefik.http.routers.homelab.rule=Host(`home.maggielab.org`)"
        - "traefik.http.routers.homelab.entrypoints=websecure"
        - "traefik.http.routers.homelab.tls=false"
        - "traefik.http.routers.homelab.service=homelab"
        - "traefik.swarm.network=monitor"
      restart_policy:
        condition: on-failure
    volumes:
      - /mnt/nfs/docker/configs/homepage/public/images/:/app/public/images
      -  /mnt/nfs/docker/configs/homepage:/app/config # Make sure your local config directory exists
    environment:
      HOMEPAGE_ALLOWED_HOSTS: home.maggielab.org
      PUID: 1000
      PGID: 1000
