global:
  checkNewVersion: false
  sendAnonymousUsage: false

accessLog: {}

log:
  level: DEBUG

api:
  dashboard: true
  insecure: false
  debug: true

entryPoints:
  web:
    address: :80
    http:
      redirections:
          entrypoint:
            to: websecure
            scheme: https
            permanent: true
  websecure:
    address: :443
    http:
      tls: true
  metrics:
    address: :8082

metrics:
  prometheus:
    buckets: [.1,0.3,1.2,5.0]
    entryPoint: metrics
    addEntryPointsLabels: true

providers:
  swarm:
    exposedByDefault: false
    endpoint: 'tcp://192.168.0.10:2375'
    watch: true
    network: monitor
  file:
    directory: /etc/traefik/dynamic
    watch: true
