{
 "title": "Docker Swarm Monitoring",
 "description": "Docker monitoring with Prometheus and cAdvisor",
 "tags": [ "docker" ],
 "time": { "from": "now-1m", "to": "now" },
 "panels": [
  { "title": "Docker Swarm", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Running containers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(container_last_seen{image!=\"\", image!~\".*cadvisor\"})"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "stat",
   "gridPos": { "h": 4, "w": 9, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{image!=\"\", image!~\".*cadvisor\"})",
     "legendFormat": "Usage"
    },
    {
     "expr": "sum(machine_memory_bytes{job=\"$cluster\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Swarm CPU Usage (%)",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(rate(container_cpu_user_seconds_total{image!=\"\", image!~\".*cadvisor\", }[2m])) / sum (machine_cpu_cores)) * 100"
    }
   ]
  },
  {
   "title": "Swarm Memory Usage (%)",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{image!=\"\", image!~\".*cadvisor\"}) / sum(machine_memory_bytes) * 100"
    }
   ]
  },
  {
   "title": "Container Resource Allocation and Usage",
   "type": "table",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "label_replace(rate(container_cpu_user_seconds_total{image!=\"\", image!~\".*cadvisor\", image!=\"\"}[2m]), \"node\", \"$1\", \"instance\", \"(.*):48080\")"
    },
    {
     "expr": "container_memory_working_set_bytes{image!=\"\", image!~\".*cadvisor\", image!=\"\"}"
    },
    {
     "expr": "((container_spec_memory_limit_bytes{image!=\"\", image!~\".*cadvisor\"} == 0) + on (instance) group_left(image) (machine_memory_bytes)) OR (container_spec_memory_limit_bytes{image!=\"\", image!~\".*cadvisor\"} > 0)"
    },
    {
     "expr": "time() - container_start_time_seconds{image!=\"\", image!~\".*cadvisor\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_user_seconds_total{image!=\"\", image!~\".*cadvisor\"}[2m])) by (container_label_com_docker_swarm_service_name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{image!=\"\", image!~\".*cadvisor\", image!=\"\"}) by (container_label_com_docker_swarm_service_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network Rx",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(irate(container_network_receive_bytes_total{image!=\"\", image!~\".*cadvisor\"}[5m])) by (container_label_com_docker_swarm_service_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network Tx",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(irate(container_network_transmit_bytes_total{image!=\"\", image!~\".*cadvisor\",}[5m])) by (container_label_com_docker_swarm_service_name)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}